.PHONY: clean All

All:
	@echo "----------Building project:[ ControlFlow - Debug ]----------"
	@cd "ControlFlow" && "$(MAKE)" -f  "ControlFlow.mk"
clean:
	@echo "----------Cleaning project:[ ControlFlow - Debug ]----------"
	@cd "ControlFlow" && "$(MAKE)" -f  "ControlFlow.mk" clean
